parameters:
#    haynner_client.example.class: Haynner\ClientBundle\Example

services:
#    haynner_client.example:
#        class: %haynner_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
