haynner_client:
    resource: "@HaynnerClientBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: HaynnerUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout